name: Promote

on:
  push:
    branches:
    - "!*" # do not run for branches
    tags:
    - "*"  # run for tags

jobs:
  #
  #
  # Promote tagged releases
  # from `dev.catalog.kubestack.com` to `catalog.kubestack.com`
  promote:
    runs-on: ubuntu-latest
    needs: publish
    # promote only for tags
    if: startsWith(github.ref, 'refs/tags/')

    steps:
    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.5.1
      with:
        service_account_key: ${{ secrets.GCLOUD_AUTH }}

    # Promote archive
    - run: |
            export NAME=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            set +e
            while true
            do
                gsutil cp gs://dev.catalog.kubestack.com/${NAME}.zip gs://catalog.kubestack.com/${NAME}.zip &&\
                gsutil cp gs://dev.catalog.kubestack.com/module-${NAME}.zip gs://catalog.kubestack.com/module-${NAME}.zip &&\
                break
                sleep 15
            done

    # Check promotion
    - name: Check promotion
      run: |
            export NAME=$(echo $GITHUB_REF | sed -e "s#^refs/tags/##")
            wget https://storage.googleapis.com/catalog.kubestack.com/module-${NAME}.zip
